[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "strategy_backtester"
version = "0.1.0"
description = "Strategy backtest framework for testing and evaluating trading strategies."
requires-python = ">=3.9"
dependencies = [
    "numpy",
    "yfinance",
    "pandas",
    "pyyaml",
    "lxml"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["strategy_backtester*"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]