import pandas as pd
import numpy as np
from core.types import PortfolioWeights, ExecutionResult
from portfolio.portfolio import PortfolioState

# Cost parameters (should be moved to config)
# Expressed in basis points (1 bp = 0.01%)
COMMISSION_BPS = 5.0 # Per-side, per trade
SPREAD_BPS = 5.0 # Per-side
SLIPPAGE_K = 0.1
ADV_WINDOW = 20
BPS = 1e-4


def execute(
    pending: PortfolioWeights,
    state: PortfolioState,
    open_prices: pd.Series,
    hist_prices: pd.DataFrame,
    date: pd.Timestamp,
    commission_bps: float = COMMISSION_BPS,
    spread_bps: float = SPREAD_BPS,
    slippage_k: float = SLIPPAGE_K,
    adv_window: int = ADV_WINDOW
) -> ExecutionResult:
    """
    Execute pending orders at T+1 open and compute transaction costs.

    Parameters
    ----------
    pending : PortfolioWeights
        Target weights generated by strategy at end of day T for T+1.
    state : PortfolioState
        Portfolio state at end of day T / start of day T+1.
    open_prices : pd.Series
        Open prices for T+1, execution occurs at these prices.
    hist_prices : pd.DataFrame
        Historical prices up to and including T.
    date : pd.Timestamp
        Date of execution (T+1).
    commission_bps : float, Optional
        Per-side commission in basis points, default COMMISSION_BPS.
    spread_bps : float, Optional
        Per-side half bid-ask spread in basis points, default SPREAD_BPS.
    slippage_k : float, Optional
        Market impact coefficient, default SLIPPAGE_K. Slippage = k * (order / ADV).
    adv_window : int, Optional
        Number of days to use for average daily volume computation, default ADV_WINDOW.
    
    Returns
    -------
    ExecutionResult
        Result of execution, including fills and costs.
    """
    total_value = state.total_value

    # Compute weight deltas and filter out phantom trades
    target = pending.combined
    current = state.current_weights
    all_tickers = target.index.union(current.index)
    target = target.reindex(all_tickers, fill_value=0.0)
    current = current.reindex(all_tickers, fill_value=0.0)

    weight_delta = target - current
    weight_delta = weight_delta[weight_delta.abs() > BPS]
    if weight_delta.empty:
        return _no_trade_result(date)

    # Check for missing open prices for execution tickers
    exec_prices = open_prices.reindex(weight_delta.index)
    missing = exec_prices[exec_prices.isna()].index.tolist()
    if missing:
        raise ValueError(f"Missing open prices for tickers: {missing}")
    
    # Convert weight deltas to shares
    trade_values = weight_delta * total_value
    fills_shares = trade_values / exec_prices

    # Compute costs
    abs_trade_values = trade_values.abs()
    adv = _compute_adv(hist_prices, weight_delta.index, adv_window)
    commission = _compute_commission(abs_trade_values, total_value, commission_bps)
    spread = _compute_spread(abs_trade_values, total_value, spread_bps)
    slippage = _compute_slippage(abs_trade_values, adv, total_value, slippage_k)
    turnover = float(abs_trade_values.sum() / total_value)

    return ExecutionResult(
        date = date,
        fills = fills_shares,
        execution_prices = exec_prices,
        turnover = turnover,
        slippage = slippage,
        commission = commission,
        spread = spread
    )


def _compute_adv(
    hist_prices: pd.DataFrame,
    tickers: pd.Index,
    adv_window: int
) -> pd.Series:
    """
    Compute average daily volume (ADV) for each ticker.

    Parameters
    ----------
    hist_prices : pd.DataFrame
        Historical prices up to and including T.
    tickers : pd.Index
        Tickers to compute ADV for.
    adv_window : int
        Number of days to use for ADV computation.
    
    Returns
    -------
    pd.Series
        Average daily volume for each ticker.
    """
    fallback = 1_000_000.0
    adv = {}

    for ticker in tickers:
        try:
            close = hist_prices[('adj_close', ticker)].iloc[-adv_window:]
            volume = hist_prices[('volume', ticker)].iloc[-adv_window:]
            daily_dollar_volume = (close * volume).dropna()
            adv[ticker] = float(daily_dollar_volume.mean()) if not daily_dollar_volume.empty else fallback
        except KeyError:
            adv[ticker] = fallback

    return pd.Series(adv)


def _compute_commission(
    abs_trade_values: pd.Series,
    total_value: float,
    commission_bps: float
) -> float:
    """Flat per-side commission as fraction of portfolio value."""
    return float(abs_trade_values.sum() * commission_bps * BPS / total_value)


def _compute_spread(
    abs_trade_values: pd.Series,
    total_value: float,
    spread_bps: float
) -> float:
    """Flat per-side spread as fraction of portfolio value."""
    return float(abs_trade_values.sum() * spread_bps * BPS / total_value)


def _compute_slippage(
    abs_trade_values: pd.Series,
    adv: pd.Series,
    total_value: float,
    slippage_k: float
) -> float:
    """Slippage = k * (order / ADV) as fraction of portfolio value."""
    participation = abs_trade_values / adv.reindex(abs_trade_values.index)
    slippage = slippage_k * participation * abs_trade_values
    return float(slippage.sum() / total_value)


def _no_trade_result(date: pd.Timestamp) -> ExecutionResult:
    """No trade result when all weight deltas are below noise threshold."""
    return ExecutionResult(
        date = date,
        fills = pd.Series(dtype=float),
        execution_prices = pd.Series(dtype=float),
        costs = 0.0,
        turnover = 0.0,
        slippage = 0.0,
        commission = 0.0
    )