from __future__ import annotations
import pandas as pd
import yaml
import os
from strategy_backtester.data import PriceDataFrame, get_field
from strategy_backtester.core import PortfolioWeights, ExecutionResult
from strategy_backtester.portfolio import PortfolioState

BPS = 1e-4                # One basis point — used in cost computations
_TRADE_THRESHOLD = 1e-4   # Minimum weight delta to execute a new trade (1 bps)
_CLOSE_THRESHOLD = 1e-6   # Weight residual below which a position is treated as closed

# Load execution parameters from config.yaml
_CONFIG_PATH = os.path.join(os.path.dirname(__file__), "..", "configs", "config.yaml")
_CONFIG_PATH = os.path.normpath(_CONFIG_PATH)
def _load_execution_config() -> dict:
    with open(_CONFIG_PATH) as f:
        return yaml.safe_load(f)["execution"]
_cfg = _load_execution_config()
COMMISSION_BPS = _cfg["commission_bps"]
SPREAD_BPS = _cfg["spread_bps"]
SLIPPAGE_K = _cfg["slippage_k"]
ADV_WINDOW = _cfg["adv_window"]


def execute(
    pending: PortfolioWeights,
    state: PortfolioState,
    open_prices: pd.Series,
    hist_prices: PriceDataFrame,
    date: pd.Timestamp,
    commission_bps: float = COMMISSION_BPS,
    spread_bps: float = SPREAD_BPS,
    slippage_k: float = SLIPPAGE_K,
    adv_window: int = ADV_WINDOW
) -> ExecutionResult:
    """
    Execute pending orders at T+1 open and compute transaction costs.

    Parameters
    ----------
    pending : PortfolioWeights
        Target weights generated by strategy at end of day T for T+1.
    state : PortfolioState
        Portfolio state at end of day T / start of day T+1.
    open_prices : pd.Series
        Open prices for T+1, execution occurs at these prices.
    hist_prices : PriceDataFrame
        Historical prices up to and including T.
    date : pd.Timestamp
        Date of execution (T+1).
    commission_bps : float, Optional
        Per-side commission in basis points, default COMMISSION_BPS.
    spread_bps : float, Optional
        Per-side half bid-ask spread in basis points, default SPREAD_BPS.
    slippage_k : float, Optional
        Market impact coefficient, default SLIPPAGE_K. Slippage = k * (order / ADV).
    adv_window : int, Optional
        Number of days to use for average daily volume computation, default ADV_WINDOW.
    
    Returns
    -------
    ExecutionResult
        Result of execution, including fills and costs.
    """
    total_value = state.total_value

    # Compute weight deltas and filter out phantom trades
    target = pending.combined
    current = state.current_weights
    all_tickers = target.index.union(current.index)
    target = target.reindex(all_tickers, fill_value=0.0)
    current = current.reindex(all_tickers, fill_value=0.0)

    weight_delta = target - current
    is_closing = (target.abs() <= _CLOSE_THRESHOLD) & (current.abs() > _CLOSE_THRESHOLD)
    is_meaningful = weight_delta.abs() > _TRADE_THRESHOLD
    weight_delta = weight_delta[is_meaningful | is_closing]
    if weight_delta.empty:
        return _no_trade_result(date)

    # Check for missing open prices for execution tickers
    exec_prices = open_prices.reindex(weight_delta.index)
    missing = exec_prices[exec_prices.isna()].index.tolist()
    if missing:
        raise ValueError(f"Missing open prices for tickers: {missing}")
    
    # Convert weight deltas to shares
    trade_values = weight_delta * total_value
    fills_shares = trade_values / exec_prices

    closing_mask = is_closing.reindex(weight_delta.index, fill_value = False)
    if closing_mask.any():
        closing_tickers = closing_mask[closing_mask].index
        fills_shares[closing_tickers] = -state.positions.reindex(closing_tickers, fill_value=0.0)
        trade_values[closing_tickers] = fills_shares[closing_tickers] * exec_prices[closing_tickers]

    # Compute costs
    abs_trade_values = trade_values.abs()
    adv = _compute_adv(hist_prices, weight_delta.index, adv_window)
    commission = _compute_commission(abs_trade_values, commission_bps)
    spread = _compute_spread(abs_trade_values, spread_bps)
    slippage = _compute_slippage(abs_trade_values, adv, slippage_k)
    turnover = float(abs_trade_values.sum() / total_value)

    return ExecutionResult(
        date = date,
        fills = fills_shares,
        execution_prices = exec_prices,
        turnover = turnover,
        slippage = slippage,
        commission = commission,
        spread = spread
    )


def _compute_adv(
    hist_prices: PriceDataFrame,
    tickers: pd.Index,
    adv_window: int
) -> pd.Series:
    """
    Compute average daily volume (ADV) for each ticker.

    Parameters
    ----------
    hist_prices : PriceDataFrame
        Historical prices up to and including T.
    tickers : pd.Index
        Tickers to compute ADV for.
    adv_window : int
        Number of days to use for ADV computation.
    
    Returns
    -------
    pd.Series
        Average daily volume for each ticker.
    """
    fallback = 1_000_000.0
    close = get_field(hist_prices, "Close")
    volume = get_field(hist_prices, "Volume")
    known_tickers = tickers[tickers.isin(close.columns)]
    adv = pd.Series(fallback, index=tickers)
    if not known_tickers.empty:
        dollar_vol = (
            close.iloc[-adv_window:][known_tickers] *
            volume.iloc[-adv_window:][known_tickers]
        ).mean()
        adv[known_tickers] = dollar_vol.fillna(fallback)
    return adv


def _compute_commission(
    abs_trade_values: pd.Series,
    commission_bps: float
) -> float:
    """Flat per-side commission."""
    return float(abs_trade_values.sum() * commission_bps * BPS)


def _compute_spread(
    abs_trade_values: pd.Series,
    spread_bps: float
) -> float:
    """Flat per-side spread."""
    return float(abs_trade_values.sum() * spread_bps * BPS)


def _compute_slippage(
    abs_trade_values: pd.Series,
    adv: pd.Series,
    slippage_k: float
) -> float:
    """Slippage = k * (order / ADV)."""
    participation = abs_trade_values / adv.reindex(abs_trade_values.index)
    slippage = slippage_k * participation * abs_trade_values
    return float(slippage.sum())


def _no_trade_result(date: pd.Timestamp) -> ExecutionResult:
    """No trade result when all weight deltas are below noise threshold."""
    return ExecutionResult(
        date = date,
        fills = pd.Series(dtype=float),
        execution_prices = pd.Series(dtype=float),
        turnover = 0.0,
        slippage = 0.0,
        commission = 0.0,
        spread = 0.0
    )